#############################################################################
# Makefile for building: getmewheels2
# Generated by qmake (2.01a) (Qt 4.7.3) on: Wed Feb 8 00:09:57 2012
# Project:  getmewheels2.pro
# Template: app
# Command: /home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/bin/qmake -spec ../QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/mkspecs/symbian-sbsv2 -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o bld.inf getmewheels2.pro
#############################################################################

MAKEFILE          = Makefile
QMAKE             = /home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/bin/qmake
DEL_FILE          = rm -f
DEL_DIR           = rmdir
CHK_DIR_EXISTS    = test -d
MKDIR             = mkdir -p
MOVE              = mv
DEBUG_PLATFORMS   = winscw gcce armv5 armv6
RELEASE_PLATFORMS = gcce armv5 armv6
MAKE              = make
SBS               = sbs

DEFINES	 = -DSYMBIAN -DUNICODE -DQT_KEYPAD_NAVIGATION -DQT_SOFTKEYS_ENABLED -DQT_USE_MATH_H_FLOATS -DQT_DECLARATIVE_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
INCPATH	 =  -I"/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/include/QtCore"  -I"/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/include/QtNetwork"  -I"/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/include/QtGui"  -I"/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/include/QtDeclarative"  -I"/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/include"  -I"/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/mkspecs/common/symbian"  -I"/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/epoc32/include"  -I"/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/stdapis"  -I"/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/stdapis/sys"  -I"/home/micha/Develop/getmewheels2/qmlapplicationviewer"  -I"/home/micha/Develop/qoauth"  -I"/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/mw"  -I"/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/mw"  -I"/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform"  -I"/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/loc"  -I"/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/mw/loc"  -I"/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/loc/sc"  -I"/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/mw/loc/sc"  -I"/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/stdapis/stlportv5"  -I"/home/micha/Develop/getmewheels2/moc"  -I"/home/micha/Develop/getmewheels2"  -I"/home/micha/Develop/getmewheels2/data"  -I"/home/micha/Develop/getmewheels2/engines"  -I"/home/micha/Develop/getmewheels2/engines/car2go"  -I"/home/micha/Develop/getmewheels2/oauth"  -I"/home/micha/Develop/getmewheels2/rcc"  -I"/home/micha/Develop/getmewheels2/ui" 
first: default

all: debug release

default: debug-winscw
qmake:
	$(QMAKE) "/home/micha/Develop/getmewheels2/getmewheels2.pro"  -spec ../QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/mkspecs/symbian-sbsv2 -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

bld.inf: /home/micha/Develop/getmewheels2/getmewheels2.pro
	$(QMAKE) "/home/micha/Develop/getmewheels2/getmewheels2.pro"  -spec ../QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/mkspecs/symbian-sbsv2 -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

/home/micha/Develop/getmewheels2/getmewheels2.loc: 
	$(QMAKE) "/home/micha/Develop/getmewheels2/getmewheels2.pro"  -spec ../QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/mkspecs/symbian-sbsv2 -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

debug: /home/micha/Develop/getmewheels2/getmewheels2.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
clean-debug: bld.inf
	$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
freeze-debug: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
release: /home/micha/Develop/getmewheels2/getmewheels2.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1
clean-release: bld.inf
	$(SBS) reallyclean --toolcheck=off -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1
freeze-release: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

debug-winscw: /home/micha/Develop/getmewheels2/getmewheels2.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc
clean-debug-winscw: bld.inf
	$(SBS) reallyclean -c winscw_udeb.mwccinc
freeze-debug-winscw: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc
debug-gcce: /home/micha/Develop/getmewheels2/getmewheels2.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-gcce: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
debug-armv5: /home/micha/Develop/getmewheels2/getmewheels2.loc bld.inf
	$(SBS) -c armv5_udeb
clean-debug-armv5: bld.inf
	$(SBS) reallyclean -c armv5_udeb
freeze-debug-armv5: bld.inf
	$(SBS) freeze -c armv5_udeb
debug-armv6: /home/micha/Develop/getmewheels2/getmewheels2.loc bld.inf
	$(SBS) -c armv6_udeb
clean-debug-armv6: bld.inf
	$(SBS) reallyclean -c armv6_udeb
freeze-debug-armv6: bld.inf
	$(SBS) freeze -c armv6_udeb
release-gcce: /home/micha/Develop/getmewheels2/getmewheels2.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-gcce: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
release-armv5: /home/micha/Develop/getmewheels2/getmewheels2.loc bld.inf
	$(SBS) -c armv5_urel
clean-release-armv5: bld.inf
	$(SBS) reallyclean -c armv5_urel
freeze-release-armv5: bld.inf
	$(SBS) freeze -c armv5_urel
release-armv6: /home/micha/Develop/getmewheels2/getmewheels2.loc bld.inf
	$(SBS) -c armv6_urel
clean-release-armv6: bld.inf
	$(SBS) reallyclean -c armv6_urel
freeze-release-armv6: bld.inf
	$(SBS) freeze -c armv6_urel
debug-armv5-gcce4.4.1: /home/micha/Develop/getmewheels2/getmewheels2.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
release-armv5-gcce4.4.1: /home/micha/Develop/getmewheels2/getmewheels2.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
debug-armv6-gcce4.4.1: /home/micha/Develop/getmewheels2/getmewheels2.loc bld.inf
	$(SBS) -c arm.v6.udeb.gcce4_4_1
clean-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.udeb.gcce4_4_1
freeze-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.udeb.gcce4_4_1
release-armv6-gcce4.4.1: /home/micha/Develop/getmewheels2/getmewheels2.loc bld.inf
	$(SBS) -c arm.v6.urel.gcce4_4_1
clean-release-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.urel.gcce4_4_1
freeze-release-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.urel.gcce4_4_1

export: bld.inf
	$(SBS) export -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

cleanexport: bld.inf
	$(SBS) cleanexport -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

freeze: freeze-release

check: first

run:
	call /home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/epoc32/release/winscw/udeb/getmewheels2.exe $(QT_RUN_OPTIONS)

runonphone: sis
	runonphone $(QT_RUN_ON_PHONE_OPTIONS) --sis getmewheels2.sis getmewheels2.exe $(QT_RUN_OPTIONS)

getmewheels2_template.pkg: /home/micha/Develop/getmewheels2/getmewheels2.pro
	$(MAKE) -f $(MAKEFILE) qmake

getmewheels2_installer.pkg: /home/micha/Develop/getmewheels2/getmewheels2.pro
	$(MAKE) -f $(MAKEFILE) qmake

getmewheels2_stub.pkg: /home/micha/Develop/getmewheels2/getmewheels2.pro
	$(MAKE) -f $(MAKEFILE) qmake

sis: getmewheels2_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_sis:
	/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/bin/createpackage -g $(QT_SIS_OPTIONS) getmewheels2_template.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_sis: getmewheels2_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_unsigned_sis:
	/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/bin/createpackage -g $(QT_SIS_OPTIONS) -o getmewheels2_template.pkg $(QT_SIS_TARGET)

getmewheels2.sis:
	$(MAKE) -f $(MAKEFILE) sis

installer_sis: getmewheels2_installer.pkg sis
	$(MAKE) -f $(MAKEFILE) ok_installer_sis

ok_installer_sis: getmewheels2_installer.pkg
	/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/bin/createpackage $(QT_SIS_OPTIONS) getmewheels2_installer.pkg - $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_installer_sis: getmewheels2_installer.pkg unsigned_sis
	$(MAKE) -f $(MAKEFILE) ok_unsigned_installer_sis

ok_unsigned_installer_sis: getmewheels2_installer.pkg
	/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/bin/createpackage $(QT_SIS_OPTIONS) -o getmewheels2_installer.pkg

fail_sis_nocache:
	$(error Project has to be built or QT_SIS_TARGET environment variable has to be set before calling 'SIS' target)

stub_sis: getmewheels2_stub.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_stub_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_stub_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_stub_sis:
	/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/bin/createpackage -s $(QT_SIS_OPTIONS) getmewheels2_stub.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

deploy:
	@echo Deployment not supported in this environment

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc/moc_qmlapplicationviewer.cpp moc/moc_mapwidget.cpp moc/moc_gmwmarker.cpp moc/moc_core.cpp moc/moc_gmwitemmodel.cpp moc/moc_gmwitem.cpp moc/moc_gmwvehicle.cpp moc/moc_gmwparkingspot.cpp moc/moc_gmwgasstation.cpp moc/moc_gmwbooking.cpp moc/moc_gmwitemsortfilterproxymodel.cpp moc/moc_gmwengine.cpp moc/moc_car2goengine.cpp moc/moc_settings.cpp moc/moc_location.cpp moc/moc_engineplugin.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_qmlapplicationviewer.cpp moc/moc_mapwidget.cpp moc/moc_gmwmarker.cpp moc/moc_core.cpp moc/moc_gmwitemmodel.cpp moc/moc_gmwitem.cpp moc/moc_gmwvehicle.cpp moc/moc_gmwparkingspot.cpp moc/moc_gmwgasstation.cpp moc/moc_gmwbooking.cpp moc/moc_gmwitemsortfilterproxymodel.cpp moc/moc_gmwengine.cpp moc/moc_car2goengine.cpp moc/moc_settings.cpp moc/moc_location.cpp moc/moc_engineplugin.cpp
moc/moc_qmlapplicationviewer.cpp: qmlapplicationviewer/qmlapplicationviewer.h
	/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/bin/moc $(DEFINES) $(INCPATH) -DSYMBIAN /home/micha/Develop/getmewheels2/qmlapplicationviewer/qmlapplicationviewer.h -o /home/micha/Develop/getmewheels2/moc/moc_qmlapplicationviewer.cpp

moc/moc_mapwidget.cpp: data/gmwitemmodel.h \
		data/gmwitem.h \
		engines/gmwengine.h \
		engines/engineplugin.h \
		engines/location.h \
		data/gmwaccount.h \
		data/gmwvehicle.h \
		data/gmwbooking.h \
		data/gmwgasstation.h \
		data/gmwparkingspot.h \
		data/gmwbusinessarea.h \
		data/gmwitemsortfilterproxymodel.h \
		gmwmarker.h \
		mapwidget.h
	/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/bin/moc $(DEFINES) $(INCPATH) -DSYMBIAN /home/micha/Develop/getmewheels2/mapwidget.h -o /home/micha/Develop/getmewheels2/moc/moc_mapwidget.cpp

moc/moc_gmwmarker.cpp: data/gmwitem.h \
		gmwmarker.h
	/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/bin/moc $(DEFINES) $(INCPATH) -DSYMBIAN /home/micha/Develop/getmewheels2/gmwmarker.h -o /home/micha/Develop/getmewheels2/moc/moc_gmwmarker.cpp

moc/moc_core.cpp: data/gmwitemmodel.h \
		data/gmwitem.h \
		engines/gmwengine.h \
		engines/engineplugin.h \
		engines/location.h \
		data/gmwaccount.h \
		data/gmwvehicle.h \
		data/gmwbooking.h \
		data/gmwgasstation.h \
		data/gmwparkingspot.h \
		data/gmwbusinessarea.h \
		data/gmwitemsortfilterproxymodel.h \
		core.h
	/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/bin/moc $(DEFINES) $(INCPATH) -DSYMBIAN /home/micha/Develop/getmewheels2/core.h -o /home/micha/Develop/getmewheels2/moc/moc_core.cpp

moc/moc_gmwitemmodel.cpp: data/gmwitem.h \
		engines/gmwengine.h \
		engines/engineplugin.h \
		engines/location.h \
		data/gmwaccount.h \
		data/gmwvehicle.h \
		data/gmwbooking.h \
		data/gmwgasstation.h \
		data/gmwparkingspot.h \
		data/gmwbusinessarea.h \
		data/gmwitemmodel.h
	/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/bin/moc $(DEFINES) $(INCPATH) -DSYMBIAN /home/micha/Develop/getmewheels2/data/gmwitemmodel.h -o /home/micha/Develop/getmewheels2/moc/moc_gmwitemmodel.cpp

moc/moc_gmwitem.cpp: data/gmwitem.h
	/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/bin/moc $(DEFINES) $(INCPATH) -DSYMBIAN /home/micha/Develop/getmewheels2/data/gmwitem.h -o /home/micha/Develop/getmewheels2/moc/moc_gmwitem.cpp

moc/moc_gmwvehicle.cpp: data/gmwitem.h \
		data/gmwbooking.h \
		data/gmwaccount.h \
		data/gmwvehicle.h
	/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/bin/moc $(DEFINES) $(INCPATH) -DSYMBIAN /home/micha/Develop/getmewheels2/data/gmwvehicle.h -o /home/micha/Develop/getmewheels2/moc/moc_gmwvehicle.cpp

moc/moc_gmwparkingspot.cpp: data/gmwitem.h \
		data/gmwparkingspot.h
	/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/bin/moc $(DEFINES) $(INCPATH) -DSYMBIAN /home/micha/Develop/getmewheels2/data/gmwparkingspot.h -o /home/micha/Develop/getmewheels2/moc/moc_gmwparkingspot.cpp

moc/moc_gmwgasstation.cpp: data/gmwitem.h \
		data/gmwgasstation.h
	/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/bin/moc $(DEFINES) $(INCPATH) -DSYMBIAN /home/micha/Develop/getmewheels2/data/gmwgasstation.h -o /home/micha/Develop/getmewheels2/moc/moc_gmwgasstation.cpp

moc/moc_gmwbooking.cpp: data/gmwaccount.h \
		data/gmwbooking.h
	/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/bin/moc $(DEFINES) $(INCPATH) -DSYMBIAN /home/micha/Develop/getmewheels2/data/gmwbooking.h -o /home/micha/Develop/getmewheels2/moc/moc_gmwbooking.cpp

moc/moc_gmwitemsortfilterproxymodel.cpp: data/gmwitem.h \
		data/gmwitemmodel.h \
		engines/gmwengine.h \
		engines/engineplugin.h \
		engines/location.h \
		data/gmwaccount.h \
		data/gmwvehicle.h \
		data/gmwbooking.h \
		data/gmwgasstation.h \
		data/gmwparkingspot.h \
		data/gmwbusinessarea.h \
		data/gmwitemsortfilterproxymodel.h
	/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/bin/moc $(DEFINES) $(INCPATH) -DSYMBIAN /home/micha/Develop/getmewheels2/data/gmwitemsortfilterproxymodel.h -o /home/micha/Develop/getmewheels2/moc/moc_gmwitemsortfilterproxymodel.cpp

moc/moc_gmwengine.cpp: engines/engineplugin.h \
		engines/location.h \
		data/gmwaccount.h \
		data/gmwvehicle.h \
		data/gmwitem.h \
		data/gmwbooking.h \
		data/gmwgasstation.h \
		data/gmwparkingspot.h \
		data/gmwbusinessarea.h \
		engines/gmwengine.h
	/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/bin/moc $(DEFINES) $(INCPATH) -DSYMBIAN /home/micha/Develop/getmewheels2/engines/gmwengine.h -o /home/micha/Develop/getmewheels2/moc/moc_gmwengine.cpp

moc/moc_car2goengine.cpp: engines/gmwengine.h \
		engines/engineplugin.h \
		engines/location.h \
		data/gmwaccount.h \
		data/gmwvehicle.h \
		data/gmwitem.h \
		data/gmwbooking.h \
		data/gmwgasstation.h \
		data/gmwparkingspot.h \
		data/gmwbusinessarea.h \
		QtOAuth/QtOAuth \
		QtOAuth/interface.h \
		QtOAuth/qoauth_global.h \
		QtOAuth/qoauth_namespace.h \
		oauth/oauth.h \
		engines/car2go/car2goengine.h
	/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/bin/moc $(DEFINES) $(INCPATH) -DSYMBIAN /home/micha/Develop/getmewheels2/engines/car2go/car2goengine.h -o /home/micha/Develop/getmewheels2/moc/moc_car2goengine.cpp

moc/moc_settings.cpp: engines/location.h \
		settings.h
	/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/bin/moc $(DEFINES) $(INCPATH) -DSYMBIAN /home/micha/Develop/getmewheels2/settings.h -o /home/micha/Develop/getmewheels2/moc/moc_settings.cpp

moc/moc_location.cpp: engines/location.h
	/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/bin/moc $(DEFINES) $(INCPATH) -DSYMBIAN /home/micha/Develop/getmewheels2/engines/location.h -o /home/micha/Develop/getmewheels2/moc/moc_location.cpp

moc/moc_engineplugin.cpp: engines/location.h \
		data/gmwaccount.h \
		data/gmwvehicle.h \
		data/gmwitem.h \
		data/gmwbooking.h \
		data/gmwgasstation.h \
		data/gmwparkingspot.h \
		engines/engineplugin.h
	/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/bin/moc $(DEFINES) $(INCPATH) -DSYMBIAN /home/micha/Develop/getmewheels2/engines/engineplugin.h -o /home/micha/Develop/getmewheels2/moc/moc_engineplugin.cpp

compiler_rcc_make_all: rcc/qrc_getmewheels2.cpp
compiler_rcc_clean:
	-$(DEL_FILE) rcc/qrc_getmewheels2.cpp
rcc/qrc_getmewheels2.cpp: getmewheels2.qrc \
		qml/getmewheels2/images/car_map.png \
		qml/getmewheels2/images/location_mark.png \
		qml/getmewheels2/images/gas_map_l.png \
		qml/getmewheels2/images/parking_cp_map.png \
		qml/getmewheels2/images/parking_cp_map_l.png \
		qml/getmewheels2/images/car_map_l.png \
		qml/getmewheels2/images/gas_map.png \
		qml/getmewheels2/images/squircle_s_gray.png \
		qml/getmewheels2/images/car_ed_map.png \
		qml/getmewheels2/images/parking_map_l.png \
		qml/getmewheels2/images/parking_map.png \
		qml/getmewheels2/images/car_ed_map_l.png
	/home/micha/Develop/QtSDK_symbian/Symbian/SDKs/SymbianSR1Qt474/bin/rcc -name getmewheels2 /home/micha/Develop/getmewheels2/getmewheels2.qrc -o /home/micha/Develop/getmewheels2/rcc/qrc_getmewheels2.cpp

compiler_image_collection_make_all: ui/qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui/qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

dodistclean:
	-if test -e /home/micha/Develop/getmewheels2/getmewheels2_template.pkg; then $(DEL_FILE)  /home/micha/Develop/getmewheels2/getmewheels2_template.pkg; fi
	-if test -e /home/micha/Develop/getmewheels2/getmewheels2_stub.pkg; then $(DEL_FILE)  /home/micha/Develop/getmewheels2/getmewheels2_stub.pkg; fi
	-if test -e /home/micha/Develop/getmewheels2/getmewheels2_installer.pkg; then $(DEL_FILE)  /home/micha/Develop/getmewheels2/getmewheels2_installer.pkg; fi
	-if test -e /home/micha/Develop/getmewheels2/Makefile; then $(DEL_FILE)  /home/micha/Develop/getmewheels2/Makefile; fi
	-if test -e /home/micha/Develop/getmewheels2/getmewheels2_exe.mmp; then $(DEL_FILE)  /home/micha/Develop/getmewheels2/getmewheels2_exe.mmp; fi
	-if test -e /home/micha/Develop/getmewheels2/getmewheels2_reg.rss; then $(DEL_FILE)  /home/micha/Develop/getmewheels2/getmewheels2_reg.rss; fi
	-if test -e /home/micha/Develop/getmewheels2/getmewheels2.rss; then $(DEL_FILE)  /home/micha/Develop/getmewheels2/getmewheels2.rss; fi
	-if test -e /home/micha/Develop/getmewheels2/getmewheels2.loc; then $(DEL_FILE)  /home/micha/Develop/getmewheels2/getmewheels2.loc; fi
	-if test -e /home/micha/Develop/getmewheels2/bld.inf; then $(DEL_FILE)  /home/micha/Develop/getmewheels2/bld.inf; fi

distclean: clean dodistclean

clean: bld.inf
	-$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1


